In [26]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [21]:
!pip install ucimlrepo

Collecting ucimlrepo
  Downloading ucimlrepo-0.0.7-py3-none-any.whl.metadata (5.5 kB)
Requirement already satisfied: pandas>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from ucimlrepo) (2.2.2)
Requirement already satisfied: certifi>=2020.12.5 in /usr/local/lib/python3.12/dist-packages (from ucimlrepo) (2026.2.25)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.0->ucimlrepo) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.0->ucimlrepo) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.0->ucimlrepo) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.0->ucimlrepo) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.0.0->ucimlrepo) (1.17.0)
Downloading ucimlrepo-0.0.7-py3-none-any.whl (8.0 kB)
Installing collected packages: ucimlrepo
Successfully installed ucimlrepo-0.0.7

In [28]:
#importer les packages
import numpy as np
import pandas as pd
from scipy import stats
from ucimlrepo import fetch_ucirepo

# fetch dataset
regensburg_pediatric_appendicitis = fetch_ucirepo(id=938)

# data (as pandas dataframes)
X = regensburg_pediatric_appendicitis.data.features
y = regensburg_pediatric_appendicitis.data.targets

# metadata
print(regensburg_pediatric_appendicitis.metadata)
print(regensburg_pediatric_appendicitis.variables)

{'uci_id': 938, 'name': 'Regensburg Pediatric Appendicitis', 'repository_url': 'https://archive.ics.uci.edu/dataset/938/regensburg+pediatric+appendicitis', 'data_url': 'https://archive.ics.uci.edu/static/public/938/data.csv', 'abstract': 'This repository holds the data from a cohort of pediatric patients with suspected appendicitis admitted with abdominal pain to Children’s Hospital St. Hedwig in Regensburg, Germany, between 2016 and 2021. Each patient has (potentially multiple) ultrasound (US) images, aka views, tabular data comprising laboratory, physical examination, scoring results and ultrasonographic findings extracted manually by the experts, and three target variables, namely, diagnosis, management and severity.', 'area': 'Health and Medicine', 'tasks': ['Classification'], 'characteristics': ['Tabular', 'Image'], 'num_instances': 782, 'num_features': 53, 'feature_types': ['Real', 'Categorical', 'Integer'], 'demographics': ['Age', 'Sex'], 'target_col': ['Management', 'Severity', 'Diagnosis'], 'index_col': None, 'has_missing_values': 'yes', 'missing_values_symbol': 'NaN', 'year_of_dataset_creation': 2023, 'last_updated': 'Tue Feb 06 2024', 'dataset_doi': '10.5281/zenodo.7669442', 'creators': ['Ricards Marcinkevics', 'Patricia Reis', 'Ugne Klimiene', 'Ece Ozkan', 'Kieran Chin-Cheong', 'Alyssia Paschke', 'Julia Zerres', 'Markus Denzinger', 'David Niederberger', 'S. Wellmann', 'C. Knorr', 'Julia E.'], 'intro_paper': {'ID': 354, 'type': 'NATIVE', 'title': 'Interpretable and Intervenable Ultrasonography-based Machine Learning Models for Pediatric Appendicitis', 'authors': 'Ricards Marcinkevics, Patricia Reis Wolfertstetter, Ugne Klimiene, Ece Ozkan, Kieran Chin-Cheong, Alyssia Paschke, Julia Zerres, Markus Denzinger, David Niederberger, S. Wellmann, C. Knorr, Julia E. Vogt', 'venue': 'Medical Image Analysis', 'year': 2023, 'journal': None, 'DOI': None, 'URL': 'https://arxiv.org/abs/2302.14460v2', 'sha': None, 'corpus': None, 'arxiv': None, 'mag': None, 'acl': None, 'pmid': None, 'pmcid': None}, 'additional_info': {'summary': 'This dataset was acquired in a retrospective study from a cohort of pediatric patients admitted with abdominal pain to Children’s Hospital St. Hedwig in Regensburg, Germany. Multiple abdominal B-mode ultrasound images were acquired for most patients, with the number of views varying from 1 to 15. The images depict various regions of interest, such as the abdomen’s right lower quadrant, appendix, intestines, lymph nodes and reproductive organs. Alongside multiple US images for each subject, the dataset includes information encompassing laboratory tests, physical examination results, clinical scores, such as Alvarado and pediatric appendicitis scores, and expert-produced ultrasonographic findings. Lastly, the subjects were labeled w.r.t. three target variables: diagnosis (appendicitis vs. no appendicitis), management (surgical vs. conservative) and severity (complicated vs. uncomplicated or no appendicitis). The study was approved by the Ethics Committee of the University of Regensburg (no. 18-1063-101, 18-1063_1-101 and 18-1063_2-101) and was performed following applicable guidelines and regulations.', 'purpose': None, 'funded_by': None, 'instances_represent': None, 'recommended_data_splits': None, 'sensitive_data': None, 'preprocessing_description': None, 'variable_info': None, 'citation': None}, 'external_url': 'https://zenodo.org/records/7669442'}
                                name     role         type demographic  \
0                                Age  Feature   Continuous         Age
1                                BMI  Feature   Continuous        None
2                                Sex  Feature  Categorical         Sex
3                             Height  Feature   Continuous        None
4                             Weight  Feature      Integer        None
5                     Length_of_Stay  Feature      Integer        None
6                         Management   Target  Categorical        None
7                           Severity   Target  Categorical        None
8              Diagnosis_Presumptive    Other       Binary        None
9                          Diagnosis   Target       Binary        None
10                    Alvarado_Score  Feature      Integer        None
11     Paedriatic_Appendicitis_Score  Feature      Integer        None
12                    Appendix_on_US  Feature       Binary        None
13                 Appendix_Diameter  Feature      Integer        None
14                    Migratory_Pain  Feature       Binary        None
15              Lower_Right_Abd_Pain  Feature       Binary        None
16  Contralateral_Rebound_Tenderness  Feature       Binary        None
17                     Coughing_Pain  Feature       Binary        None
18                            Nausea  Feature       Binary        None
19                  Loss_of_Appetite  Feature       Binary        None
20                  Body_Temperature  Feature   Continuous        None
21                         WBC_Count  Feature   Continuous        None
22             Neutrophil_Percentage  Feature      Integer        None
23             Segmented_Neutrophils  Feature      Integer        None
24                      Neutrophilia  Feature  Categorical        None
25                         RBC_Count  Feature   Continuous        None
26                        Hemoglobin  Feature   Continuous        None
27                               RDW  Feature   Continuous        None
28                 Thrombocyte_Count  Feature      Integer        None
29                  Ketones_in_Urine  Feature  Categorical        None
30                      RBC_in_Urine  Feature  Categorical        None
31                      WBC_in_Urine  Feature  Categorical        None
32                               CRP  Feature      Integer        None
33                           Dysuria  Feature       Binary        None
34                             Stool  Feature  Categorical        None
35                       Peritonitis  Feature  Categorical        None
36                        Psoas_Sign  Feature  Categorical        None
37    Ipsilateral_Rebound_Tenderness  Feature  Categorical        None
38                      US_Performed  Feature  Categorical        None
39                         US_Number    Other      Integer        None
40                       Free_Fluids  Feature  Categorical        None
41              Appendix_Wall_Layers  Feature  Categorical        None
42                       Target_Sign  Feature  Categorical        None
43                     Appendicolith  Feature  Categorical        None
44                         Perfusion  Feature  Categorical        None
45                       Perforation  Feature  Categorical        None
46       Surrounding_Tissue_Reaction  Feature  Categorical        None
47              Appendicular_Abscess  Feature  Categorical        None
48                  Abscess_Location  Feature  Categorical        None
49          Pathological_Lymph_Nodes  Feature       Binary        None
50              Lymph_Nodes_Location  Feature  Categorical        None
51             Bowel_Wall_Thickening  Feature       Binary        None
52       Conglomerate_of_Bowel_Loops  Feature       Binary        None
53                             Ileus  Feature  Categorical        None
54                       Coprostasis  Feature  Categorical        None
55                         Meteorism  Feature  Categorical        None
56                         Enteritis  Feature  Categorical        None
57            Gynecological_Findings  Feature  Categorical        None

                                          description  units missing_values
0                     Obtained from the date of birth  years            yes
1   Measures body fat; patient's weight divided by...   None            yes
2                                   Registered gender   None            yes
3                                    Patient's height   None            yes
4                                    Patient's weight   None            yes
5                  Length of the stay in the hospital   None            yes
6   (conservative, primary surgical, secondary sur...   None            yes
7   (uncomplicated, complicated) Severity of appen...   None            yes
8                       Patient's suspected diagnosis   None            yes
9   Patient's diagnosis, histologically confirmed ...   None            yes
10    Patient's score according to the scoring system   None            yes
11    Patient's score according to the scoring system   None            yes
12  Detectability of the vermiform appendix during...   None            yes
13             Maximal outer diameter of the appendix   None            yes
14  Abdominal pain; usually starts in epigastrium ...   None            yes
15       Right iliac fossa pain detected on palpation   None            yes
16  A state in which pain of the contralateral sid...   None            yes
17                     Abdominal pain by forced cough   None            yes
18  Feeling of sickness/ejection of contents from ...   None            yes
19                                               None   None            yes
20  Measured by a thermometer placed in the rectum...   None            yes
21  The number of leucocytes in a unit volume of b...   None            yes
22              Mature WBC in the granulocytic series   None            yes
23  Most mature neutrophilic granulocytes present ...   None            yes
24  Relative neutrophilic leucocytosis, often a re...   None            yes
25  The number of erythrocytes in a unit volume of...   None            yes
26  Hemoglobin level; a red protein in the red blo...   None            yes
27  A blood test that measures the differences in ...   None            yes
28  The number of platelets in a unit volume of blood   None            yes
29  Presence of ketone bodies in urine, e.g. in ca...   None            yes
30                                     Blood in urine   None            yes
31    Leucocytes in urine, e.g., in case of infection   None            yes
32  Protein produced by the liver, elevated in cas...   None            yes
33          Pain or other difficulty during urination   None            yes
34                 Characteristics of bowel movements   None            yes
35  Spasm of abdominal wall muscles detected on pa...   None            yes
36    Abdominal pain produced by extension of the hip   None            yes
37  A state in which pain of the ipsilateral side ...   None            yes
38  If an abdominal ultrasonography was performed ...   None            yes
39                                               None   None            yes
40                     Free fluids inside the abdomen   None            yes
41  Distribution and characteristics of appendix l...   None            yes
42  Axial image of appendix with a fluid-filled ce...   None            yes
43  Presence of fecalith in the appendix, e.g. aco...   None            yes
44                    Blood flow to the appendix wall   None            yes
45                Signs of appendix perforation in US   None            yes
46  Inflammation signs in tissue (i.a. in omentum/...   None            yes
47                                   Appendiceal mass   None            yes
48             Location of the abcess intraperitoneal   None            yes
49  Enlarged and inflamed intra-abdominal lymph nodes   None            yes
50  The location of pathological lymph nodes in th...   None            yes
51  Edema of the intestinal wall, > 2-3 mm for sma...   None            yes
52  Small intestine conglomerate as sign of intrap...   None            yes
53  Sonographic signs of paralytic ileus (e.g., di...   None            yes
54                       Fecal impaction in the colon   None            yes
55               Accumulation of gas in the intestine   None            yes
56  Sonographic features of gastroenteritis, e.g. ...   None            yes
57  Gynaecological abnormalities, e.g. cysts, ovar...   None            yes

In [29]:
#ouvrir la base de données
df=pd.read_excel("/content/app_data.xlsx")
df
df.shape
df.info
df.describe()

,Age,BMI,Height,Weight,Length_of_Stay,Alvarado_Score,Paedriatic_Appendicitis_Score,Appendix_Diameter,Body_Temperature,WBC_Count,Neutrophil_Percentage,Segmented_Neutrophils,RBC_Count,Hemoglobin,RDW,Thrombocyte_Count,CRP,US_Number
count,781.000000,755.000000,756.000000,779.000000,778.000000,730.000000,730.000000,498.000000,775.000000,776.000000,679.000000,54.000000,764.000000,764.000000,756.000000,764.000000,771.000000,760.000000
mean,11.346483,18.906916,148.017460,43.172542,4.284062,5.921918,5.253425,7.762651,37.404516,12.670683,71.791163,64.929630,4.799490,13.380497,13.180291,285.252618,31.387899,425.515789
std,3.529979,4.385252,19.732016,17.390984,2.574057,2.155972,1.958456,2.536671,0.903678,5.366525,14.463656,15.085025,0.499012,1.393271,4.538774,72.494373,57.433588,271.585211
min,0.000000,7.827983,53.000000,3.960000,1.000000,0.000000,0.000000,2.700000,26.900000,2.600000,27.200000,32.000000,3.620000,8.200000,11.200000,91.000000,0.000000,1.000000
25%,9.200000,15.725294,137.000000,29.500000,3.000000,4.000000,4.000000,6.000000,36.800000,8.200000,61.400000,54.500000,4.537500,12.600000,12.300000,236.000000,1.000000,198.750000
50%,11.438741,18.062284,149.650000,41.400000,3.000000,6.000000,5.000000,7.500000,37.200000,12.000000,75.500000,64.500000,4.780000,13.300000,12.700000,276.000000,7.000000,398.500000
75%,14.099932,21.179011,163.000000,54.000000,5.000000,8.000000,7.000000,9.100000,37.900000,16.200000,83.600000,77.500000,5.020000,14.000000,13.300000,330.000000,33.000000,613.250000
max,18.360000,38.156221,192.000000,103.000000,28.000000,10.000000,10.000000,17.000000,40.200000,37.700000,97.700000,91.000000,14.000000,36.000000,86.900000,708.000000,365.000000,992.000000

In [30]:
#supprimer les lignes repetées
df.duplicated().sum()

np.int64(0)

In [31]:
#découverte des valeurs manquantes
df.isnull().sum()

Age                                   1
BMI                                  27
Sex                                   2
Height                               26
Weight                                3
Length_of_Stay                        4
Management                            1
Severity                              1
Diagnosis_Presumptive                 2
Diagnosis                             2
Alvarado_Score                       52
Paedriatic_Appendicitis_Score        52
Appendix_on_US                        5
Appendix_Diameter                   284
Migratory_Pain                        9
Lower_Right_Abd_Pain                  8
Contralateral_Rebound_Tenderness     15
Coughing_Pain                        16
Nausea                                8
Loss_of_Appetite                     10
Body_Temperature                      7
WBC_Count                             6
Neutrophil_Percentage               103
Segmented_Neutrophils               728
Neutrophilia                         50
RBC_Count                            18
Hemoglobin                           18
RDW                                  26
Thrombocyte_Count                    18
Ketones_in_Urine                    200
RBC_in_Urine                        206
WBC_in_Urine                        199
CRP                                  11
Dysuria                              29
Stool                                17
Peritonitis                           9
Psoas_Sign                           37
Ipsilateral_Rebound_Tenderness      163
US_Performed                          4
US_Number                            22
Free_Fluids                          63
Appendix_Wall_Layers                564
Target_Sign                         644
Appendicolith                       713
Perfusion                           719
Perforation                         701
Surrounding_Tissue_Reaction         530
Appendicular_Abscess                697
Abscess_Location                    769
Pathological_Lymph_Nodes            579
Lymph_Nodes_Location                661
Bowel_Wall_Thickening               683
Conglomerate_of_Bowel_Loops         739
Ileus                               722
Coprostasis                         711
Meteorism                           642
Enteritis                           716
Gynecological_Findings              756
dtype: int64

In [32]:
#gestion des valeurs manquantes

  #gestion des variables manquantes de type faible et modéré

      #gestion des variables de type numérique
colonnes_continues = [
    'Appendix_Diameter', 'Neutrophil_Percentage', 'Alvarado_Score',
    'Paedriatic_Appendicitis_Score', 'BMI', 'Height', 'RDW',
    'US_Number', 'Hemoglobin', 'Thrombocyte_Count', 'RBC_Count',
    'CRP', 'Body_Temperature', 'WBC_Count', 'Length_of_Stay',
    'Weight', 'Age'
]

for col in colonnes_continues:
    df[col] = df[col].fillna(df[col].median())

     #gestion des variables catégorielles
colonnes_cat = ['RBC_in_Urine','Ketones_in_Urine','WBC_in_Urine','Ipsilateral_Rebound_Tenderness'
    'Sex', 'Diagnosis', 'Severity', 'Management', 'Neutrophilia',
    'Migratory_Pain', 'Lower_Right_Abd_Pain', 'Contralateral_Rebound_Tenderness',
    'Coughing_Pain', 'Nausea', 'Loss_of_Appetite', 'Dysuria',
    'Stool', 'Peritonitis', 'Psoas_Sign', 'Appendix_on_US',
    'US_Performed', 'Free_Fluids','Diagnosis_Presumptive']

for col in colonnes_cat:
    if col in df.columns:
        df[col] = df[col].fillna(df[col].mode()[0])

In [33]:
#gestion des variables de type critique
colonnes_critiques = [
    'Abscess_Location', 'Gynecological_Findings', 'Conglomerate_of_Bowel_Loops',
    'Segmented_Neutrophils', 'Ileus', 'Perfusion', 'Enteritis', 'Appendicolith',
    'Coprostasis', 'Perforation', 'Appendicular_Abscess', 'Bowel_Wall_Thickening',
    'Lymph_Nodes_Location', 'Target_Sign', 'Meteorism', 'Pathological_Lymph_Nodes',
    'Appendix_Wall_Layers', 'Surrounding_Tissue_Reaction']

df = df.drop(columns=colonnes_critiques)

In [34]:
#gestion des valeurs aberrantes
   #Détection par IQR
colonnes_numeriques = [
    'Age', 'BMI', 'CRP', 'WBC_Count', 'Hemoglobin',
    'Body_Temperature', 'RDW', 'Appendix_Diameter',
    'Alvarado_Score', 'Paedriatic_Appendicitis_Score',
    'Length_of_Stay', 'Weight', 'Height', 'RBC_Count',
    'Thrombocyte_Count', 'Neutrophil_Percentage'
]

for col in colonnes_numeriques:
    s = df[col].dropna()
    Q1, Q3 = s.quantile(0.25), s.quantile(0.75)
    IQR = Q3 - Q1
    bb, bh = Q1 - 1.5*IQR, Q3 + 1.5*IQR
    n = ((s < bb) | (s > bh)).sum()
    print(f'{col}: {n} outliers | bornes=[{bb:.2f}, {bh:.2f}]')

 #suppression des valeurs biologiques impossibles
df = df[df['Body_Temperature'] > 34]
df = df[df['Hemoglobin'] <= 20]
df = df[df['RDW'] <= 30]
df = df[df['RBC_Count'] <= 8]

print(f'Lignes restantes : {len(df)}')

 #Winnorisation
colonnes_winsor = ['BMI', 'WBC_Count', 'Length_of_Stay',
                   'Thrombocyte_Count', 'Appendix_Diameter']

for col in colonnes_winsor:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    borne_basse = Q1 - 1.5 * IQR
    borne_haute = Q3 + 1.5 * IQR
    df[col] = df[col].clip(lower=borne_basse, upper=borne_haute)

Age: 5 outliers | bornes=[1.90, 21.39]
BMI: 30 outliers | bornes=[7.99, 28.83]
CRP: 91 outliers | bornes=[-45.50, 78.50]
WBC_Count: 7 outliers | bornes=[-3.55, 28.05]
Hemoglobin: 26 outliers | bornes=[10.75, 15.95]
Body_Temperature: 12 outliers | bornes=[35.15, 39.55]
RDW: 23 outliers | bornes=[10.80, 14.80]
Appendix_Diameter: 217 outliers | bornes=[5.50, 9.50]
Alvarado_Score: 0 outliers | bornes=[-2.00, 14.00]
Paedriatic_Appendicitis_Score: 14 outliers | bornes=[1.00, 9.00]
Length_of_Stay: 44 outliers | bornes=[0.00, 8.00]
Weight: 8 outliers | bornes=[-7.25, 90.75]
Height: 15 outliers | bornes=[101.66, 198.56]
RBC_Count: 15 outliers | bornes=[3.84, 5.71]
Thrombocyte_Count: 9 outliers | bornes=[96.88, 467.88]
Neutrophil_Percentage: 5 outliers | bornes=[36.00, 110.20]
Lignes restantes : 776

In [35]:
colonnes_a_supprimer = list(set([
    'Peritonitis', 'Weight', 'Height', 'Alvarado_Score', 'Neutrophilia', 'Stool', 'RBC_Count', 'Paedriatic_Appendicitis_Score',
    'Management', 'Severity', 'Length_of_Stay', 'Diagnosis_Presumptive', 'US_Number', 'CRP_log'
]))
df = df.drop(columns=[col for col in colonnes_a_supprimer if col in df.columns])
print(df.shape)
print(df.columns)

(776, 27)
Index(['Age', 'BMI', 'Sex', 'Diagnosis', 'Appendix_on_US', 'Appendix_Diameter',
       'Migratory_Pain', 'Lower_Right_Abd_Pain',
       'Contralateral_Rebound_Tenderness', 'Coughing_Pain', 'Nausea',
       'Loss_of_Appetite', 'Body_Temperature', 'WBC_Count',
       'Neutrophil_Percentage', 'Hemoglobin', 'RDW', 'Thrombocyte_Count',
       'Ketones_in_Urine', 'RBC_in_Urine', 'WBC_in_Urine', 'CRP', 'Dysuria',
       'Psoas_Sign', 'Ipsilateral_Rebound_Tenderness', 'US_Performed',
       'Free_Fluids'],
      dtype='object')

In [ ]:
df.to_excel('app_data_sans_critiques.xlsx', index=False)
print(f'Fichier sauvegardé : {df.shape[0]} lignes, {df.shape[1]} colonnes')

#test